### ISSUE TITLE
Document what’s going on with the `TONE_DATA` arrays?

### ISSUE THREAD

**Issue by Mr0grog** [hsivonen/detone#1]
Hi, I was recently doing some work with encoding in Windows-1258, and this library was a very helpful and interesting read. Thanks! 🙇

However, I spent a fair amount of time puzzling over the [`TONE_DATA` arrays](https://github.com/hsivonen/detone/blob/9c407c2d6c98ae4109215466af9020f4ffedef24/src/lib.rs#L23-L193) and how they work. Would you accept a PR that just adds explanatory comments to them (I’d be happy to author it), so future readers can grasp it more quickly than me?

For example, my notes about `TONE_DATA.extensions_for_vietnamese` are basically:

```rust
// Decompositions for characters in main range of composed vowels + accents +
// tone marks that are used for Vietnamese, code points 0x1ea0 - 0x1efa.
//
// Decompositions are listed in order, so the decomposition for code point
// 0x1ea0 is at index 0, 0x1ea0 is at index 1, etc.
//
// Each decomposition is a bitmap, where the lower 10 bits indicate the code
// point of the "base" character (e.g. "A" for "Ạ") and the upper bits indicate
// the code point for a follow-on "combining" character (e.g. 0x0323, or
// "Combining dot below" for "Ạ"), offset by negative 0x0300 (the offset just
// saves us some bits).
//
// For example, the decomposition of 0x1ea0 ("Ạ") is 0x8c41, which represents
// the base character 0x0041 and the combining character 0x0323:
//
//     0x8c41  =  0b_1000_1100_0100_0001
//     Base:      0b_0000_0000_0100_0001 = 0x41
//                          ^^^^^^^^^^^    (Lower 10 bits)
//     Combining: 0b_1000_11             = 0x23 + 0x300 = 0x0323
//                   ^^^^^^^               (Upper bits)
```

A couple side questions:

- I originally thought these values might have come from somewhere else, given what *seemed* to me like a unusual and complex way to pack the data together instead of just using a container type like a tuple of `(base_code_point, tone_mark_code_point)`. But I never found anything else that looked like these; is it just something you did to save a little memory?

- ~Is there a reason the values in `TONE_DATA.middle_key` are offset by 0xC3 (so they start at 0), but the values in `TONE_DATA.windows_1258_key` are not (even though they work similarly)? I figured this was just an artifact of learning from one after writing the other, but didn’t know if there was some intentional reason I was missing (and that I should document if I add comments).~ *(Edit: nevermind, I just realized this is pretty obviously because the `middle_key` values would have to be u16 instead of u8 if they weren’t offset.)*

**Comment by Mr0grog** [comment]
Nevermind the the second question. I just looked at this again with fresh eyes and realized it was pretty obviously because the `middle_key` values would have to be u16 without the offset. D'oh! 🤦

**Comment by hsivonen** [comment]
This is just something that I did to make things more compact than storing pairs of `char`. (Whether this was a good idea is debatable. It just seemed sad to waste the bits.)

I'd accept a PR to document the bit layout.

**Comment by Mr0grog** [comment]
Makes sense; thanks for the explanation. You’ll see a PR from me soon. :)
